version: '3.3'
services:

  gateway:
    container_name: gateway
    image: nginx:1.19-alpine
    ports:
      - "80:80"

    depends_on:
      - distributor.backend
      - assembler.collector

    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/www:/var/www
      - ./gateway/log:/var/log/nginx

  distributor.backend:
    build: ./distributor/backend
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper
    ports:
      - "6000:6000"
    volumes:
      - ./distributor/backend/main.py:/app/distributor/backend/main.py
      - ./shared/trie.py:/app/distributor/backend/trie.py
      - ./shared/shared_tries:/app/distributor/backend/shared_tries
    command: gunicorn --chdir /app/distributor/backend main:app -b 0.0.0.0:6000 --reload

  assembler.collector:
    build: ./assembler/collector
    ports:
      - "5000:5000"
    volumes:
      - ./assembler/collector/main.py:/app/assembler/collector/main.py
      - ./shared/trie.py:/app/assembler/collector/trie.py
      - ./shared/shared_phrases:/app/assembler/collector/shared_phrases
    command: gunicorn --chdir /app/assembler/collector main:app -b 0.0.0.0:5000 --reload
  
  assembler.triebuilder:
    build: ./assembler/triebuilder
    environment:
      - ZOOKEEPER_HOST=zookeeper
    depends_on:
      - zookeeper
    volumes:
      - ./assembler/triebuilder/main.py:/app/assembler/triebuilder/main.py
      - ./shared/trie.py:/app/assembler/triebuilder/trie.py
      - ./shared/shared_targets:/app/assembler/triebuilder/shared_targets
      - ./shared/shared_tries:/app/assembler/triebuilder/shared_tries
    command: python /app/assembler/triebuilder/main.py
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000